### ISSUE TITLE
People are insisting on comparing with emotion :)

### ISSUE THREAD

**Issue by kof** [tuchk4/css-in-js-app#11]

**Comment by tuchk4** [comment]
Will add emotions at the start of next week, after my vacation :)

**Comment by tuchk4** [comment]
oh I didn't see #10 using my phone.

**Comment by tuchk4** [comment]
Like to merge PR in this way :)

![image](https://user-images.githubusercontent.com/5140611/32485565-8f3f6694-c3ac-11e7-890e-6e6c705ec736.png)

**Comment by kof** [comment]
perfect timing!

**Comment by tuchk4** [comment]
Deployed https://tuchk4.github.io/css-in-js-app/#/emotion
