### ISSUE TITLE
Please rename jss to react-jss

### ISSUE THREAD

**Issue by kof** [tuchk4/css-in-js-app#4]
Because what you currently use is not directly jss core.
Also please add jss without default-preset and with default-preset. Because it actually implements a lot more stuff compared to other libs.

**Comment by tuchk4** [comment]
- [x] renamed into `react-jss`. https://tuchk4.github.io/css-in-js-app/#/react-jss
- [x] added `react-jss-w/o-plugins` https://tuchk4.github.io/css-in-js-app/#/react-jss-wihtout-plugins

**Comment by kof** [comment]
- typo: ReactJssWihtoutPlugins
- broken link to https://github.com/tuchk4/css-in-js-app/blob/master/src/scenes/jss/block.js
- broken link  to https://github.com/tuchk4/css-in-js-app/blob/master/src/scenes/jss/differentBlocks.js
- broken link to https://github.com/tuchk4/css-in-js-app/blob/master/src/scenes/styled-jss/block.js

Basically all links to the source are broken.

**Comment by kof** [comment]
Also are you interested in tests without react?

**Comment by tuchk4** [comment]
> Basically all links to the source are broken.

Yeah my bad. I renamed all components to uppercase style but forgot to fix these links. Now should be ok.

> Also are you interested in tests without react?

I think a bit later I will make similar app but without React lib.
